### ISSUE TITLE
SDDM theme does not work after new changes in NixOS.

### ISSUE THREAD

**Issue by Linux-DADDY** [Zhaith-Izaliel/sddm-sugar-candy-nix#1]
Hey, I have followed your guide from your github which is still not working, I am on NixOS latest stable branch. Here is my flake config.
```nix
# input
sddm-sugar-candy-nix = {
      url = "gitlab:Zhaith-Izaliel/sddm-sugar-candy-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
```nix
# Output
    sddm-sugar-candy-nix,
```
```nix
# Module
        sddm-sugar-candy-nix.nixosModules.default
        {
          nixpkgs = {
            overlays = [
              sddm-sugar-candy-nix.overlays.default
            ];
          };
        }
```
Global config, It does not work even if i add the `services.xserver.displayManager.sddm.sugarCandyNix`
```nix
  services.displayManager.sddm.sugarCandyNix = {
    enable = true; # This enables SDDM automatically and set its theme to
    # "sddm-sugar-candy-nix"
    settings = {
      # Set your configuration options here.
      # Here is a simple example:
      Background = lib.cleanSource ./background.png;
      ScreenWidth = 1920;
      ScreenHeight = 1080;
      FormPosition = "left";
      HaveFormBackground = true;
      PartialBlur = true;
      # ...
    };
  }; 
```
And here is the errors 
```nix
# Command
sudo nixos-rebuild test 
```
```nix
# Outputs of Command
error:
       … while calling the 'seq' builtin

         at /nix/store/p648p3av68k4h6li0126ddkznmr1mj2s-source/lib/modules.nix:320:18:

          319|         options = checked options;
          320|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          321|         _module = checked (config._module);

       … while calling the 'throw' builtin

         at /nix/store/p648p3av68k4h6li0126ddkznmr1mj2s-source/lib/modules.nix:296:18:

          295|                     ''
          296|             else throw baseMsg
             |                  ^
          297|         else null;

       error: The option `services.displayManager.sddm.enable' does not exist. Definition values:
       - In `/nix/store/p648p3av68k4h6li0126ddkznmr1mj2s-source/flake.nix':
           {
             _type = "if";
             condition = true;
             content = true;
           }
```

**Comment by Zhaith-Izaliel** [comment]
Hi,

This problem comes from a mismatch between your nixpkgs unstable revision and the flake. You see, the option `services.displayManager.sddm.enable` is only available in the latest versions of nixpkgs. You should update your nixpkgs input using `nix flake lock --update-input nixpkgs`.

Alternatively, if you don't want to update your nixpkgs input, you can select the release 2.5.1, as it uses the old options for sddm, ie. `services.xserver.displayManager.sddm.*`.

To do that, you have to change the input as follows:

```nix
# input
sddm-sugar-candy-nix = {
      url = "gitlab:Zhaith-Izaliel/sddm-sugar-candy-nix/v2.5.1";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

If I find a way to allow old options to be selected without breaking the module, I'll do it. But as of now, I don't have that much time to fix it, so this will have to do.

Finally, you're lucky I saw your issues, I'm much more active on Gitlab and I see issues on there as soon as they are posted. This Github repo only serves as a mirror.

Best regards.

**Comment by Zhaith-Izaliel** [comment]
Great news!

I've been able to find time to fix the issue. It should work now with nixpkgs 23.11 and above without a problem!

You can try the new version 2.6.3 to test it now!
