### ISSUE TITLE
Want to say thank and suggest something to solve the caveat

### ISSUE THREAD

**Issue by bphenriques** [Zhaith-Izaliel/sddm-sugar-candy-nix#2]
Hi :wave:  

Thank you for packaging the theme, I wasn't sure how to! As suggestion, I found out that you can set `theme.conf.user` overriding the default settings as follows:
```
  environment.systemPackages = [
    self.pkgs.sddm-eucalyptus-drop # defined below
    (pkgs.writeTextDir "share/sddm/themes/sddm-eucalyptus-drop/theme.conf.user" ''
      [General]
      background=${self.pkgs.dotfiles-wallpapers}/share/wallpapers/whale-sunset.jpg
      FullBlur="true"
      PartialBlur="false"
      FormPosition="center"
    '')
  ];
```

I managed to make it work locally using a variation of your package:
```nix
{
  lib,
  stdenvNoCC,
  fetchFromGitLab,
  coreutils,
  sddm,
  qtbase,
  qtsvg,
  qtquickcontrols2,
  qtgraphicaleffects,
}:
stdenvNoCC.mkDerivation rec {
  name = "sddm-eucalyptus-drop";
  version = "2.0.0";
  src = fetchFromGitLab {
    owner = "Matt.Jolly";
    repo = "sddm-eucalyptus-drop";
    rev = "v2.0.0";
    sha256 = "wq6V3UOHteT6CsHyc7+KqclRMgyDXjajcQrX/y+rkA0=";
  };

  propagatedUserEnvPkgs = [
    sddm
    qtbase
    qtsvg
    qtgraphicaleffects
    qtquickcontrols2
  ];

  nativeBuildInputs = [
    coreutils
  ];

  installPhase = ''
    runHook preInstall
    local installDir=$out/share/sddm/themes/${name}
    mkdir -p $installDir
    cp -aR -t $installDir Main.qml Assets Components metadata.desktop theme.conf Backgrounds
    runHook postInstall
  '';

  meta = {
    description = "Eucalyptus Drop theme for SDDM";
    platforms = ["x86_64-linux"];
  };
}
``` 

This in turn solves the caveate described in the `README.md` as main theme is "fixed" and the only thing that varies is user overrides.

I personally prefer using the source directly https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop/ but want to give something in return. Ideally this should be packaged next to other themes such as `sddm-astronaut-theme` ([package](https://github.com/Keyitdev/sddm-astronaut-theme)) that I personally like as well. The `theme.conf.user` pattern is also used inside, albeit it is part of the theme package rather than separate as proposed in here. You can see these changes within a smallish patch on my personal dotfiles: https://github.com/bphenriques/dotfiles/commit/e51feff094b290453754cbaa7ab4a3549599920c

**Comment by Zhaith-Izaliel** [comment]
Hi!
Thank you for your contribution. I see what you are doing here and it's indeed much more space efficient, however I see two issues with this design:

1. Since the theme configuration and the theme "assets" are defined as two separate derivations **unrelated to each other**, the nix store can't define an explicit relationship between the two of them. Which means, for whatever reason, someone wants to remove one of the derivation manually, the other will not appear in its dependency tree and still be left as an unsuable derivation. I'm not in favor of making implicit dependencies, even though it is more space efficient.
2. In term of compatibility, this flake has 3 outputs: a package, an overlay, and module. Since multiple people are using this fork (to my surprise), I don't want to break compatibility. If someone decides to use the package directly or from the provided overlay, and overrides it to set the theme in their own module, then doing what you describe will break this usecase and I will need to provide two packages for the theme to allow the same level of compatibility. It isn't ideal.

Also, I don't think people are often building multiple variation of the same theme which sets the storage problem to the first initial tests the user will go through to set up their desired configuration. However I don't have any user data to base this point on. 

Therefore, and to keep compatibility with the provided interface, without further user data, I will keep the fork as-is.

Your suggestion is interesting and I think it could be great as a way to devise a monorepo of SDDM themes provided through an unified module system though!
